name: Publish

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    tags:
      - "v*.*.*"

jobs:
  #call_build_workflow:
  #  uses: ./.github/workflows/build.yaml

  download_artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact from build workflow
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          if_no_artifact_found: fail
          path: download

      - name: ls check
        run: ls -la download

  gh_release:
    needs: [download_artifact]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: download/
    ### make a github release with tags version and packaged artifact
