name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  call_continuous_workflow:
    uses: ./.github/workflows/ci.yaml

  publish:
    needs: [call_continuous_workflow]

    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          ### LINUX
          - build: x86_64-gnu-linux
            os: ubuntu-latest
            toolchain: stable
            target: x86_64-unknown-linux-gnu
            cross: false
            artifact_name: target/x86_64-unknown-linux-gnu/release/gitcurl
            asset_name: x86_64-gnu-linux

          - build: aarch64-gnu-linux
            os: ubuntu-latest
            toolchain: stable
            target: aarch64-unknown-linux-gnu
            cross: true
            artifact_name: target/aarch64-unknown-linux-gnu/release/gitcurl
            asset_name: aarch64-gnu-linux

          - build: x86_64-musl-linux
            os: ubuntu-latest
            toolchain: stable
            target: x86_64-unknown-linux-musl
            cross: true
            artifact_name: target/x86_64-unknown-linux-musl/release/gitcurl
            asset_name: x86_64-musl-linux

          - build: aarch64-musl-linux
            os: ubuntu-latest
            toolchain: stable
            target: aarch64-unknown-linux-musl
            cross: true
            artifact_name: target/aarch64-unknown-linux-musl/release/gitcurl
            asset_name: aarch64-musl-linux

          - build: armv7-gnu-linux
            os: ubuntu-latest
            toolchain: stable
            target: armv7-unknown-linux-gnueabihf
            cross: true
            artifact_name: target/aarch64-unknown-linux-musl/release/gitcurl
            asset_name: armv7-gnu-linux

          ### MACOS
          - build: x86_64-macos
            os: macos-latest
            toolchain: stable
            target: x86_64-apple-darwin
            cross: false
            artifact_name: target/x86_64-apple-darwin/release/gitcurl
            asset_name: x86_64-macos

          - build: aarch64-macos
            os: macos-latest
            toolchain: stable
            target: aarch64-apple-darwin
            cross: false
            artifact_name: target/aarch64-apple-darwin/release/gitcurl
            asset_name: aarch64-macos

          ### WINDOWS
          - build: x86_64-msvc-windows
            os: windows-latest
            toolchain: stable
            target: x86_64-pc-windows-msvc
            cross: false
            artifact_name: target/x86_64-pc-windows-msvc/release/gitcurl.exe
            asset_name: x86_64-msvc-windows

          ## TODO: ring need to be build for aarch64
          #- build: aarch64-msvc-windows
          #  os: windows-latest
          #  toolchain: stable
          #  target: aarch64-pc-windows-msvc
          #  cross: false
          #  artifact_name: target/aarch64-pc-windows-msvc/release/gitcurl.exe
          #  asset_name: aarch64-msvc-windows

          - build: i686-msvc-windows
            os: windows-latest
            toolchain: stable
            target: i686-pc-windows-msvc
            cross: false
            artifact_name: target/i686-pc-windows-msvc/release/gitcurl.exe
            asset_name: i686-msvc-windows

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-rust
        with:
          target: ${{ matrix.target }}
          toolchain: ${{ matrix.toolchain }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=${{ matrix.target }}
          use-cross: ${{ matrix.cross }}

      #- name: Create tar archive
      #  run: tar -czvf ${{ matrix.asset_name }}.tar.gz ${{ matrix.artifact_name }}

      - name: Upload binaries to release
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.asset_name }} #.tar.gz
          path: ${{ matrix.artifact_name }}
